name: 'dbtAC'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbtAC:
    +materialized: table
    iot:
      base:
        database: iot_base
        schema: mpl
      dwh:
        database: iot_dwh
        schema: mpl
    mpp:
      base:
        database: mpp_base
        schema: dbo
      dwh:
        database: mpp_dwh
        schema: dbo
